### ISSUE TITLE
Backend: connect the grammar / question generation functions in django to the database

### ISSUE THREAD

**Issue by jbrundrett** [H-Huang/LL1-Academy#16]
- put some dummy grammars in the database with questions for testing purposes - ask julien for help with this if needed
- develop functions so this takes into account the session object and multiple users (anonymous users at first, distinguished only by independent sessions, then eventually this will be actual users with names) can be on different sessions looking at different grammars and getting the next question will take place independently for those users

**Comment by vivz** [comment]
this is done. Users stuff should be in a separate issue
