### ISSUE TITLE
Sign in using different social media accounts at once

### ISSUE THREAD

**Issue by vincesiu** [H-Huang/LL1-Academy#49]

**Comment by vincesiu** [comment]
See [this github issue](https://github.com/pennersr/django-allauth/issues/191)

**Comment by vivz** [comment]
Should this issue be reopened or? @vincesiu

**Comment by vincesiu** [comment]
According to the github issue I linked above, one of the maintainers says that my suggestion doesn't give a good user-experience, so what we originally implemented is correct

Edit: But if we wanted, there's an open discussion with a proposed solution [here](https://github.com/pennersr/django-allauth/issues/215) which we can discuss
