### ISSUE TITLE
List of terminals does not take into account the actual terminals in the grammar

### ISSUE THREAD

**Issue by jbrundrett** [H-Huang/LL1-Academy#53]
e.g.:

![image](https://cloud.githubusercontent.com/assets/7938521/26320207/cf0a5e42-3ed6-11e7-9903-8676b819214c.png)

**Comment by jbrundrett** [comment]
clearly the only terminals in this grammar are w,z

**Comment by vivz** [comment]
is this now hardcoded in?

**Comment by vivz** [comment]
fixed the bug in the populate process. Please rerun populate
